#!/usr/bin/env bash

# ADD ADDITIONAL FEATURES
# =========================
# MINIKUBE
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube \
  && sudo -s cp minikube /usr/local/bin && rm minikube
