#!/usr/bin/env bash

# ADD ADDITIONAL FEATURES
# =========================
# DOCKER
apt-get -y update \
  && apt-get -y install curl \
  && apt-get -y install apt-transport-https \
  && apt-get -y install ca-certificates \
  && apt-get -y install gnupg \
  && apt-get -y install lsb-release \
  && apt-get -y install software-properties-common \
  && rm -rf /var/lib/apt/lists/* \
  && sudo -s groupadd docker \
  && usermod -aG docker "${USERNAME}" \
  && newgrp docker \
  && sudo -u "${USERNAME}" curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
  && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
  && apt-get -y update \
  && apt-get -y install docker.io
